# Generated by Django 6.0.1 on 2026-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="stripeevent",
            options={"ordering": ["-received_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="created",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="event_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="event_type",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="received_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
